[package]
name = "rust-playground"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "pizzeria-lib"
]


[[bin]]
name = "raw"
path = "src/raw_terminal.rs"

[dependencies]
pizzeria-lib = { path = "pizzeria-lib" }
libc = "0.2.176"
chrono = { version = "0.4", features = ["clock"] }

