[package]
name = "pizzeria-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { workspace = true }
tokio = { workspace = true, version = "1.47.1", features = ["rt", "rt-multi-thread", "macros"] }