[package]
name = "pizzeria-frontend"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "raw"
path = "src/raw_terminal.rs"

[dependencies]
pizzeria-lib = { workspace = true }
libc = { workspace = true }
tempfile = "3.23.0"
